[tool.mypy]
mypy_path = "support"
python_version = "3.8"

check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
no_warn_no_return = true
warn_unused_configs = true
